config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  resources :facilities
  resources :items, :path => 'equipment'
  resources :organizations
  resources :reservations
  resources :field_of_studies
  resources :professors
  resources :courses
  devise_scope :user do
  root to: "devise/sessions#new", :as => '/'
  end

  get '/users' => 'pages#users', :as => "users"
  get '/student/dashboard' => 'pages#dashboard'
  get '/student/reservation' => 'reservations#studentReservation'
  get '/student/reservation/:id' => 'reservations#student_view', :as => "view_reservation"
  post '/student/reservation/:id/cancel' => 'reservations#stud_cancel', :as => "student_cancel_reservation"
  get '/student/calendar' => 'pages#calendar'
  get '/student/messages' => 'pages#messages'
  get '/student/messages/:id' => 'pages#show', :as => "message_show"
  get '/admin' => 'pages#index'
  get '/admin_login' => 'pages#admin_login'
  post '/authenticate_admin' => 'pages#authenticate_admin'
  get '/admin/add_user' => 'pages#admin_add_user'
  post '/admin_create_user' => 'pages#admin_create_user'
  post '/student/see_reservations' => 'reservations#see_reservations'
  get '/student/item_list' => 'pages#item_list', :as => "item_list"
  get '/student/facility_list' => 'pages#facility_list', :as => "facility_list"
  get '/data' => 'reservations#data'
  get '/equip' => 'items#export_equipment'
  get '/equip_res' => 'items#export_equipment_pdf'  
  get '/org' => 'organizations#export_organization'
  get '/org_csv' => 'organizations#export_equipment'
  get '/prof' => 'professors#export_equipment'
  get '/prof_csv' => 'professors#export_equipment_csv'
  get '/fac' => 'facilities#export_equipment'
  get '/facs' => 'facilities#export_data'
  get '/fac_pdf' => 'facilities#export_facility_pdf'
  get '/res' => 'reservations#export_equipment'
  get '/cors' => 'courses#export_courses'
  get '/cors_csv' => 'courses#export_equipment'
  get '/res_equips' => 'items#export_equip_res'
  get '/fields' => 'field_of_studies#export_fields_pdf', :as => 'fields_export'
  get '/fields_csv' => 'field_of_studies#export_equipment'
  get '/reservation_today' => 'pages#export_reservation_today'
  get '/cancel_reservation/:id' => 'reservations#cancel', :as => 'cancel_reservation'
  post '/cancel/:id' => 'reservations#push_cancel', :as => 'submit_cancelation'
  get '/organization/new/non_acad' => 'organizations#nonAcadOrg', :as => 'non_acad'
  post '/organization/new/non_acad' => 'organizations#createNonAcadOrg', :as => 'create_non_acad'
  get '/purposes' => 'reservations#purposeForm'
  # get '/update_reservation/:id' => 'reservations#claims', as: => 'claim_time'
  post '/update_reservation/:id' => 'reservations#claims', :as => 'claim_time'
  get '/return/:id' => 'reservations#returnsView', :as => 'return'
  post '/update_reservations/:id' => 'reservations#returns', :as => 'return_time'
  post '/get_item_count' => 'reservations#get_item_count'
  # post '/cancel/:id' => 'reservations#stud_cancel', :as 'stud_cancel'
  # get '/list' => 'reservations#list' as => "list"
  # Edit non acad orgs
  get '/organization/update/:id' => 'organizations#editNonAcadOrg', :as => 'editNonAcad'
  patch '/organization/update/:id' => 'organizations#updateNonAcadOrg', :as => 'updateNonAcad'
  post '/unblock/:id' => 'pages#unblockUser', :as => 'unblock_user'
  post '/block/:id' => 'pages#blockUser', :as => "block_user"
  get "/reservation_pdf" => "reservations#reservation_pdf", as: "reservation_pdf"

  get '/show_item/:id' => "pages#item_show", as: "item_show"

  get '/facility_item/:id' => "pages#facility_show", as: "facility_show"


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get "*any", via: :all, to: "errors#not_found"


  # root to: 'devise/session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/admin_login.html.erb
<div style="background-color: maroon">
  <div class="row">
    <div class="col-lg-4 col-md-3 col-sm-3"></div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-12 mt-5 content-section" style="background-color:maroon; border-color: maroon">
      <div class="card" style="box-shadow: 0 4px 6px 0 hsla(0,0%,0%,0.2);">
        <%= form_tag authenticate_admin_path do %>
        <div class="form-group">
          <h1 class="h3 font-weight-normal card-header">Log in as Administrator</h1>
          <div class="card-body">
          <%= email_field_tag "Email", "", class: 'form-control mb-2', input_html: {autocomplete: 'off'}, placeholder: "E-mail" %>
          <%= password_field_tag "Password","", class: 'form-control mb-2', placeholder: "Password" %>
          </br>
          <%= submit_tag "LOGIN", class: 'btn btn-primary' %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-3"></div>
  </div>
</div>

app/views/pages/calendar.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
<div class="row mb-2 mt-5 pt-5">
  <%= render 'layouts/sidebar' %>
  <div class="col-9">
    <div class="card-calendar shadow p-5">
      <div id="calendar"></div>
    </div>
  </div>
</div>
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">

  </div>
<div class="modal-body">
<p></p>
</div>
</div>
</div>
</div>
</div>

app/views/pages/dashboard.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4 mt-5">
  <div class="pt-4 mt-3"><%= render 'layouts/messages' %></div>
  <%= render 'layouts/username' %>
  <div class="row mb-2">
    <%= render 'layouts/sidebar' %>
    <div class="col-9">
      <div class="card shadow">
        <div class="card-header">
          <h4>Your Reservations
            <% if current_user.block? %>
            <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#blockModal">Make Reservation</button>

            <div id="blockModal" class="modal fade" role="dialog">
              <div class="modal-dialog modal-lg">
                <div class="modal-content text-centered">
                  <div class="modal-body">
                    <p>You are blocked from PUPSJ-OEFRS.</p>
                    <p> Please approach admin to settle your account. </p>
                  </div>
                  <div class="modal-footer text-centered">

                  </div>
                </div>

              </div>
            </div>
            <% else %>
              <a href="/student/reservation" class="btn btn-success float-right">Make Reservation</a></h4>
            <% end %>
            <div class="col-6">
              <%= form_tag student_dashboard_path, class: "membership-status", method: :get do %>
                <%= select_tag "status", options_for_select(@reservation_statuses), data: { remote: true } %>
              <% end %>
            </div>
            </h4>
        </div>
        <% if @reservation.present? %>
          <div class="modal" id="memberModal", style="display: block"  >
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Successfully Created Your Reservation!</h5>
                  <button type="button" class="close", id="closeModal" aria-label="Close" onclick="closeModal()">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Please Note: <br>
                  <ul>
                    <li>YOU ARE REQUIRED TO SURRENDER YOUR I.D. UPON CLAIMING THE RESERVED EQUIPMENTS</li>
                    <li>IF YOU WILL NOT BE ABLE TO CLAIM THE RESERVED EQUIPMENT/FACILITY, PLEASE PRINT THE DOCUMENT ATTACHED TO THIS PAGE AND GIVE IT TO A REPRESENTATIVE</li>
                    <li>YOU MAY CLAIM THE EQUIPMENT 5 MINUTES BEFORE THE DESIGNATED TIME</li>
                    <li>YOU ARE GIVEN 30 MINUTES AFTER THE END TIME TO RETURN THE BORROWED EQUIPMENT; OTHERWISE, YOU WILL BE GIVEN A WARNING THAT WILL IMPEDE YOUR PRIVILEGES TO BORROW FROM THE SCHOOL</li>
                  </ul>
                </div>

                <div class="modal-footer">
                  <%= link_to "Download PDF File", reservation_pdf_path(reservation_id: @reservation.id, format: :pdf), target: 'blank', class: "btn btn-secondary" %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        <div id="studentReservationListIndex"><%= render 'student_reservation_list' %></div>
      </div>
    </div>

  </div>
</div>
</div>
</div>
<script>
</script>

app/views/pages/dashboard.js.erb
$('#studentReservationListIndex').html("<%= escape_javascript(render("student_reservation_list"))%>");

app/views/pages/facility_list.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
  <div class="row mb-2 mt-5 pt-5">
    <%= render 'layouts/sidebar' %>
    <div class="col-9">
      <h2>Facilities</h2>
      <div class="row">
        <% @facilities.each do |facility| %>
        <div class="col-6 mb-1">
            <div class="card shadow">
                <div class="card-header">
                  <b><%= facility.name %></b>
                </div>
                <div class="card-body">
                  <% facility.specifications.take(2).each do |spec| %>
                    <p><b><%= spec.field %>:</b> <%= spec.content%></p>
                  <% end %>
                   <%= link_to "See more", facility_show_path(facility.id), class: "btn btn-primary"%>
                </div>
              </div>
        </div>
        <% end %> 
    
        </div>
      
      
    </div>
  </div>
</div>

app/views/pages/facility_show.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
  <div class="row mb-2 mt-5 pt-5">
    <%= render 'layouts/sidebar' %>
    <div class="col-8 ml-4 content-section">
        <h2 class="ml-3 mt-2"><%= @facility.name %></h2>
         <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#facilityModal">See Specs</button>

            <div id="facilityModal" class="modal fade" role="dialog">
              <div class="modal-dialog modal-lg">
                <div class="modal-content text-centered">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle"><%= @facility.name %> Specifications</h5>
                </div>
                  <div class="modal-body">
                    <p> 
                      <% @facility.specifications.each do |spec| %>
                    <p><b><%= spec.field %>:</b> <%= spec.content%></p>
                  <% end %>
                    </p>
                  </div>
                  <div class="modal-footer text-centered">

                  </div>
                </div>

              </div>
            </div>
  <table class="table table-striped">
  <thead class="thead">
    <tr>
    <th>User</th>
        <th>Purpose</th>
        <th>Date</th>
        <th>Time</th>
        <th></th>
    </tr>
  </thead>
  <% @reservation_records.each do |record| %>
    <tr>
        <td><%=  
        "#{record.reservation.user.firstName} #{record.reservation.user.lastName}"  %></td>

        <td><%=  record.reservation.purpose %></td>
        <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
        <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %> - <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
    </tr>
    <% end %>
</table>


        
          </div>
        </div>
      
      
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<%= render 'layouts/navbar' %>
<header id="main-header" class="py-2 bg-danger text-white mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1><i data-feather="user"></i>Welcome Sir <%= current_user.firstName %></h1>
      </div>
    </div>
  </div>
</header>


<div class="container">
 <%= render 'layouts/messages' %>
  <div class="row">
    <div class="col-md-9">
      <div class="card">
        <div class="card-header">
          <h4>
            <%= link_to "Export Reservations for today", reservation_today_path(format: :pdf),target: 'blank', class: "btn btn-danger float-right" %>
            <%= link_to "Make Reservation", new_reservation_path, class: "mr-2 btn btn-primary float-right" %>
            Upcoming Reservations
          </h4>
        </div>
        <table class="table table-striped">
          <tr>
            <th>Reservation </th>
            <th>Date </th>
            <th>Quantity </th>
            <th>Time</th>
            <th>Reserved by</th>
          </tr>
          <% @upcoming_reservations.each do |res| %>
          <% res.reservation_records.each do |record| %>
            <tr>
                <td>
                    <%= record.facility_id.present? ? record.facility.name : record.item.name %>
                </td>
                <td> <%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
                <% if record.quantity %>
                  <td> <%= record.quantity %> </td>
                <% else %>
                  <td> N/A </td>
                <% end %>
                <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %> - <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
                <td> <%= "#{res.user&.firstName} #{res.user&.lastName}"%> </td>
            </tr>
            <% end %>
          <% end %>
        </table>
        <div>
          <ul class="apple_pagination mt-2">
          <%= will_paginate @upcoming_reservations, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card text-center bg-success text-white mb-3">
        <div class="card-body">
          <h3>Equipments</h3>
          <h1 class="display-4">
            <i data-feather='speaker'></i>
            <%= @equipment.length %>
          </h1>
          <a href="/equipment" class="btn btn-outline-light btn-sm">View</a>
        </div>
      </div>
      <div class="card text-center bg-info text-white mb-3">
        <div class="card-body">
          <h3>Facilities</h3>
          <h1 class="display-4">
            <i data-feather="home"></i>
            <%= @facilities.length %>
          </h1>
          <a href="/facilities" class="btn btn-outline-light btn-sm">View</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/item_list.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
  <div class="row mb-2 mt-5 pt-5">
    <%= render 'layouts/sidebar' %>
    <div class="col-9">
        <h2>Equipment</h2>
        <div class="row">
          <% @equipments.each do |equipment| %>
          <div class="col-6 mb-1">
            <div class="card shadow">
              <div class="card-header">
                <b><%= equipment.name %></b>
              </div>
              <div class="card-body">
                <% equipment.specifications.take(2).each do |specs| %>
                <p><b><%= specs.field %>: </b> <%= specs.content %></p>
                <% end %>
                <%= link_to "See more", item_show_path(equipment.id), class: "btn btn-primary"%>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      
      
    </div>
  </div>
</div>

app/views/pages/item_show.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
  <div class="row mb-2 mt-5 pt-5">
    <%= render 'layouts/sidebar' %>
    <div class="col-8 content-section ml-4 ">
        <h2 class="ml-3 mt-2"><%= @item.name %></h2>
        <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#itemModal">See Specs</button>

            <div id="itemModal" class="modal fade" role="dialog">
              <div class="modal-dialog modal-lg">
                <div class="modal-content text-centered">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle"><%= @item.name %> Specifications</h5>
                </div>
                  <div class="modal-body">
                    <p> 
                      <% @item.specifications.each do |spec| %>
                    <p><b><%= spec.field %>:</b> <%= spec.content%></p>
                  <% end %>
                    </p>
                  </div>
                  <div class="modal-footer text-centered">

                  </div>
                </div>

              </div>
            </div>
  <table class="table table-striped">
  <thead class="thead">
    <tr>
    <th>User</th>
        <th>Quantity </th>
        <th>Purpose</th>
        <th>Date</th>
        <th>Time</th>
        <th></th>
    </tr>
  </thead>
  <% @reservation_records.each do |record| %>
    <tr>
        <td><%=  
        "#{record.reservation.user.firstName} #{record.reservation.user.lastName}"  %></td>

        <% if record.quantity %>
          <td> <%= record.quantity %> </td>
        <% else %>
          <td> N/A </td>
        <% end %>
        <td><%=  record.reservation.purpose %></td>
        <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
        <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %> - <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
    </tr>
    <% end %>
</table>


        
          </div>
        </div>
      
      
    </div>
  </div>
</div>

app/views/pages/landingPage.html.erb
<%= render 'layouts/header' %>

<div class="container">
  <div class="row pt-5 mt-5">
    <div class="col-lg-4">
      <div class=" mt-2 content-section mb-5" style="box-shadow: 0 4px 6px 0 hsla(0,0%,0%,0.2); border-top: 6px solid maroon">
        <form method="POST">
          <div class="form-group">
            <h1 class="h3 mb-3 text-center">Log In as Student</h1>
            <hr>
            <input type="text" class="form-control mb-2 input-shadow" name='studentNumber' placeholder="Student Number" value={{request.form.studentNumber} }="}">
            <input type="password" name='password' class="form-control mb-2 input-shadow" placeholder="Password" value={{request.form.password} }="}">
            <small class="text-muted mb-2">
              <a href="{{ url_for('reset_request') }}">Forgot Password?</a>
            </small>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
            <div class="float-justify mt-2">
              <h5 class="text-center">Or</h5>
            </div>
            <div class="text-center">
              <!-- <a href="/register" class="btn btn-md btn-success btn-block">Sign Up</a> -->
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-md btn-success btn-block" %>
            </div>
            <div class="text-center">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="embed-responsive embed-responsive-16by9 mb-2 mt-2 shadow">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/37Clm7Z-fc8" allow="autoplay; encrypted-media" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/pages/list.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4 mt-5">
  <div class="pt-4 mt-3"><%= render 'layouts/messages' %></div>
  <div class="row mb-2">
    <%= render 'layouts/sidebar' %>
    <%= @facilities.each do |fac| %>
    <div class="col-4">
      <div class="card shadow">
        <div class="card-header">
          <h4> <%= fac.name %>
        </div>
        <div class="card-body">
          <%= fac.description %>
        </div>
      </div>
    </div>

  </div>
</div>
</div>
</div>

app/views/pages/show.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4">
  <div class="row mb-2 mt-5 pt-5">
    <%= render 'layouts/sidebar' %>
    <div class="col-9">
      <div class="card shadow">
        
        <% if @message.reservation_id.present? %>
        <div class="card-header">
          <h4><%= @message.title %> for <%= @reservation.dateFrom.strftime("%b %e, %Y") %></h4>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                  <th>Equipment / Facility </th>
                  <th>Quantity </th>
                  <th>Date</th>
                  <th>Time From</th>
                  <th>Time To</th>
                </tr>
            </thead>
            <% @reservation.reservation_records.each do |record| %>
              <tr>
                  <td>
                      <%= record.facility_id.present? ? record.facility.name : record.item.name %>
                  </td>
                  <% if record.quantity %>
                    <td> <%= record.quantity %> </td>
                  <% else %>
                    <td> N/A </td>
                  <% end %>
                  <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
                  <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %></td>
                  <td> <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
              </tr>
            <% end %>
            </table>
          <h5> <%= @message.content %></h5>
          <% else %>
          <div class="card-header">
          <h4><%= @message.title %></h4>
          <hr>
          <h5><%= @message.content %></h5>
          <div class="card-footer">
            <%= link_to "Back", student_dashboard_path, class: 'btn btn-secondary btn-md' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/users.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <div class="row">
    <div class="col-8"></div>
    <div class="col-4">
      <%= form_tag users_path, method: :get, class: "form-group", remote: true do %>
        <%= text_field_tag :search_trips, nil,class: "form-control", placeholder: "Search..", autocomplete: :off %>
      <% end %>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
    <h4>
    <%= link_to admin_add_user_path, class: "btn btn-success float-right" do %>
      <span class="small" data-feather="plus"></span> Add User
    <% end %>
    </h4>
    </div>
    <div id="userList"> <%= render 'users' %></div>
  </div>
</div>

app/views/pages/users.js.erb
$('#userList').html("<%= escape_javascript(render("users"))%>");