config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  resources :facilities
  resources :items, :path => 'equipment'
  resources :organizations
  resources :reservations
  resources :field_of_studies
  resources :professors
  resources :courses
  devise_scope :user do
  root to: "devise/sessions#new", :as => '/'
  end

  get '/users' => 'pages#users', :as => "users"
  get '/student/dashboard' => 'pages#dashboard'
  get '/student/reservation' => 'reservations#studentReservation'
  get '/student/reservation/:id' => 'reservations#student_view', :as => "view_reservation"
  post '/student/reservation/:id/cancel' => 'reservations#stud_cancel', :as => "student_cancel_reservation"
  get '/student/calendar' => 'pages#calendar'
  get '/student/messages' => 'pages#messages'
  get '/student/messages/:id' => 'pages#show', :as => "message_show"
  get '/admin' => 'pages#index'
  get '/admin_login' => 'pages#admin_login'
  post '/authenticate_admin' => 'pages#authenticate_admin'
  get '/admin/add_user' => 'pages#admin_add_user'
  post '/admin_create_user' => 'pages#admin_create_user'
  post '/student/see_reservations' => 'reservations#see_reservations'
  get '/student/item_list' => 'pages#item_list', :as => "item_list"
  get '/student/facility_list' => 'pages#facility_list', :as => "facility_list"
  get '/data' => 'reservations#data'
  get '/equip' => 'items#export_equipment'
  get '/equip_res' => 'items#export_equipment_pdf'  
  get '/org' => 'organizations#export_organization'
  get '/org_csv' => 'organizations#export_equipment'
  get '/prof' => 'professors#export_equipment'
  get '/prof_csv' => 'professors#export_equipment_csv'
  get '/fac' => 'facilities#export_equipment'
  get '/facs' => 'facilities#export_data'
  get '/fac_pdf' => 'facilities#export_facility_pdf'
  get '/res' => 'reservations#export_equipment'
  get '/cors' => 'courses#export_courses'
  get '/cors_csv' => 'courses#export_equipment'
  get '/res_equips' => 'items#export_equip_res'
  get '/fields' => 'field_of_studies#export_fields_pdf', :as => 'fields_export'
  get '/fields_csv' => 'field_of_studies#export_equipment'
  get '/reservation_today' => 'pages#export_reservation_today'
  get '/cancel_reservation/:id' => 'reservations#cancel', :as => 'cancel_reservation'
  post '/cancel/:id' => 'reservations#push_cancel', :as => 'submit_cancelation'
  get '/organization/new/non_acad' => 'organizations#nonAcadOrg', :as => 'non_acad'
  post '/organization/new/non_acad' => 'organizations#createNonAcadOrg', :as => 'create_non_acad'
  get '/purposes' => 'reservations#purposeForm'
  # get '/update_reservation/:id' => 'reservations#claims', as: => 'claim_time'
  post '/update_reservation/:id' => 'reservations#claims', :as => 'claim_time'
  get '/return/:id' => 'reservations#returnsView', :as => 'return'
  post '/update_reservations/:id' => 'reservations#returns', :as => 'return_time'
  post '/get_item_count' => 'reservations#get_item_count'
  # post '/cancel/:id' => 'reservations#stud_cancel', :as 'stud_cancel'
  # get '/list' => 'reservations#list' as => "list"
  # Edit non acad orgs
  get '/organization/update/:id' => 'organizations#editNonAcadOrg', :as => 'editNonAcad'
  patch '/organization/update/:id' => 'organizations#updateNonAcadOrg', :as => 'updateNonAcad'
  post '/unblock/:id' => 'pages#unblockUser', :as => 'unblock_user'
  post '/block/:id' => 'pages#blockUser', :as => "block_user"
  get "/reservation_pdf" => "reservations#reservation_pdf", as: "reservation_pdf"

  get '/show_item/:id' => "pages#item_show", as: "item_show"

  get '/facility_item/:id' => "pages#facility_show", as: "facility_show"


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get "*any", via: :all, to: "errors#not_found"


  # root to: 'devise/session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  PURPOSE = %w[ACADEMIC ORGANIZATIONAL]
  ADMIN_PURPOSE = ["ACADEMIC", "ORGANIZATIONAL", "SCHOOL EVENT"]

  belongs_to :user
  has_many :reservation_records, dependent: :destroy
  accepts_nested_attributes_for :reservation_records, :allow_destroy => true
  validates :dateFrom, presence: true
  validates :timeFrom, presence: true
  validates :timeTo, presence: true
  validates :purpose, presence: true
#  validates :sub_purpose, presence: true

  scope :upcoming, ->() { where('dateFrom >= ?', Time.zone.now) }
  scope :for_today , ->() { where('dateFrom >= ?', Time.now) }

  before_validation do
    self.errors.add(:base, "Invalid Time Range For Reservation.") if self.timeTo < self.timeFrom || self.timeFrom == self.timeTo
  end

  before_save do
    self.reference = Reservation.generate_ref_code
  end

  def self.generate_ref_code
    loop do
      random_code = SecureRandom.hex(3)
      shuffle_code = "PUPSJ-OEFRS-" + random_code.chars.shuffle!.join('')
      break shuffle_code unless self.exists?(reference: shuffle_code)
    end
  end

  def self.search(q: )
   joins(:user).where("firstName LIKE :keyword OR lastName LIKE :keyword", keyword: "%#{q}%").order(created_at: :desc)
  end


  def self.active
    self.where(status: "Active")
  end

  def self.claimed
    self.where(status: "Claimed")
  end

  def self.cancelled
    self.where(status: "Cancelled")
  end

  def self.returned
    self.where(status: "Done")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:show, :update, :edit, :destroy, :cancel, :push_cancel, :claims, :returns, :returnsView, :student_view, :stud_cancel]
  protect_from_forgery except: :studentReservation

  def index
    search = params[:search_trips]
    @reservations = if search.blank?
              if params[:status]
                if params[:status] == "all"
                  Reservation.all.paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
                else
                  Reservation.where(status: params[:status]).paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
                end
              else
                Reservation.all.paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
              end
            else
              Reservation.search(q: search).paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
            end
    @reservation_statuses = [
    ["All Reservation", "all"],
    ["Active", "Active"],
    ["Cancelled", "Canceled"],
    ["Claimed", "Claimed"],
    ["Returned", "Done"],
  ]
  end

  def new
    if params[:reservation]
      if params[:reservation][:dateFrom]
        @date_param = params.dig("reservation", "dateFrom")
        date = DateTime.parse(@date_param)
        @reservations = Reservation.where(dateFrom: date..(date + 24.hours))
        @date = date.strftime("%B %e, %Y")
        @has_picked_date = true
      elsif params[:reservation][:purpose]
        @purpose = params.dig("reservation", "purpose")
      elsif params[:reservation][:reservation_records_attributes]
        id = params[:reservation][:reservation_records_attributes].values.last[:item_id]
        quantityCount = Item.find(id.to_i).quantity
      end
    end
    @params_purpose = params[:reservation][:purpose] if params[:reservation]
    @reservation = Reservation.new
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    item_ids = []
    facility_ids = []
    errors = []
    if current_user.admin?
      error_path = new_reservation_path
      success_path = reservations_path
    else
      error_path = student_reservation_path
      success_path = student_dashboard_path
    end
    errors << "Please choose a equipment or facility to reserve" if @reservation.reservation_records.empty?
    @reservation.reservation_records.each do |x|
      item_ids << x.item_id if x.item_id
      facility_ids << x.facility_id if x.facility_id
    end

    if item_ids.uniq.length != item_ids.length || facility_ids.uniq.length != facility_ids.length
      errors << "DUPLICATE ITEM OR FACILITY"
    end
    date = @reservation.dateFrom
    @timeFrom = @reservation.timeFrom
    @timeTo = @reservation.timeTo
    @reservation.reservation_records.each do |x|
      id = x.facility_id.present? ? x.facility_id : x.item_id
      if x.facility_id.present?
        id = x.facility_id
        obj = Facility.find(id)
      else
        id = x.item_id
        obj = Item.find(id)
      end
      obj.reservation_records.each do |reserved|
        next if reserved.reservation.dateFrom != date
        if reserved.reservation.timeFrom <= @timeTo && reserved.reservation.timeTo <= @timeFrom
          if @reservation.purpose == "SCHOOL EVENT"
            reserved.reservation.update(status: "Cancelled") unless reserved.reservation.status == "SCHOOL EVENT"
            title = "Canceled Reservation"
            message_content = "Your reservation has been cancelled due to a School Event. Please approach the admin to know more."
            @message = Message.new(title: title, content: message_content, user_id: reserved.reservation.user_id, reservation_id: reserved.reservation.id)
            # binding.pry
            @message.save
            
          elsif x.quantity.present? && (reserved.quantity + x.quantity) > obj.quantity
            errors << "The Quantity Count For Your Reservation is invalid"
          elsif x.quantity.blank?
            errors << "Your Item/Facility Reservation is in conflict with existing and active reservations"
          end
        end
      end
    end
    if errors.present?
      flash[:danger] = errors.to_sentence
      return redirect_to error_path
    end
    if @reservation.save
      @reservation.update(status: "Active")
      prof = Professor.find_by(name: @reservation.sub_purpose).id if @reservation.purpose == "ACADEMIC"
      professor = Professor.find(prof)
      if professor.email != ""
        UserMailer.notify_professor(prof, @reservation.id).deliver_now! if @reservation.purpose == "ACADEMIC"
      end
      @reservation.update(academicPurpose: params[:academicPurpose]) if params[:academicPurpose].present?
      @reservation.update(academicPurpose: params[:academicPurposeCustom]) if params[:academicPurposeCustom].present?
      flash[:success] = "Successfully Created Your Reservation"
      set_path = if current_user.admin?
              reservations_path
            else
              student_dashboard_path(reservation: @reservation.id )
            end
      redirect_to set_path
    else
      flash[:danger] = @reservation.errors.full_messages.to_sentence
      redirect_to error_path
      
    end
  end

  def studentReservation
    if params[:reservation]
      if params[:reservation][:dateFrom]
        @date_param = params.dig("reservation", "dateFrom")
        date = DateTime.parse(@date_param)
        @reservations = Reservation.where(dateFrom: date..(date + 24.hours)).take(5)
        @date = date.strftime("%B %e, %Y")
        @has_picked_date = true
      elsif params[:reservation][:purpose]
        @purpose = params.dig("reservation", "purpose")
      elsif params[:reservation][:reservation_records_attributes]
        id = params[:reservation][:reservation_records_attributes].values.last[:item_id]
        quantityCount = Item.find(id.to_i).quantity
      end
    end
    @reservation = Reservation.new
  end

  def purposeForm
    @purpose = params.dig("reservation", "purpose")
  end

  def createReserevation
    @reservation = current_user.reservations.new(reservation_params)
    if @reservation.save
      redirect_to @reservation
    else
      render "new"
    end
  end

  def get_item_count
    item = Item.find(params[:item][:id])
    respond_to do |format|
      format.json { render json: item.quantity }
    end
  end

  def show
  end

  def student_view
  end

  
  def update
    item_ids = []
    facility_ids = []
    errors = []
    @reserved_items = params[:reservation][:reservation_records_attributes]
    @timeFrom = params[:reservation][:timeFrom]
    @timeTo = params[:reservation][:timeTo]
    @purpose = params[:reservation][:purpose]
    date = params[:reservation][:dateFrom]
    errors << "Please choose a equipment or facility to reserve" if @reserved_items.empty?
    @reserved_items.values.each do |x|
      item_ids << x.dig("item_id") if x.dig("item_id")
      facility_ids << x.dig("facility_id") if x.dig("facility_id")
    end
    if item_ids.uniq.length != item_ids.length || facility_ids.uniq.length != facility_ids.length
      errors << "DUPLICATE ITEM OR FACILITY"
    end

    @reserved_items.values.each do |x|
      id = x.dig("facility_id").present? ? x.dig("facility_id") : x.dig("item_id")
      if x.dig("facility_id").present?
        obj = Facility.find(id.to_i)
      else
        obj = Item.find(id.to_i)
      end
      obj.reservation_records.each do |reserved|
        next if reserved.reservation.dateFrom != date
        if reserved.reservation.timeFrom <= @timeTo && reserved.reservation.timeTo <= @timeFrom
          if @purpose == "SCHOOL EVENT"
            reserved.update(status: "CANCELLED") unless reserved.status == "SCHOOL EVENT"
          elsif x.quantity.present? && (reserved.quantity + x.quantity) > obj.quantity
            errors << "The Quantity Count For Your Reservation is invalid"
          elsif x.quantity.blank?
            errors << "Your Item/Facility Reservation is in conflict with existing and active reservations"
          end
        end
      end
    end
    if errors.present?
      flash[:danger] = errors.to_sentence
      return redirect_to error_path
    end
    if @reservation.update(reservation_params)
      @reservation.update(status: "Active")
      @reservation.update(academicPurpose: params[:academicPurpose]) if params[:academicPurpose].present?
      flash[:success] = "Successfully Updated Your Reservation"
      redirect_to reservations_path
    else
      flash[:danger] = @reservation.errors.full_messages.to_sentence
      redirect_to new_reservation_path
    end
  end

  def edit
    if params[:reservation]
      if params[:reservation][:dateFrom]
        @date_param = params.dig("reservation", "dateFrom")
        date = DateTime.parse(@date_param)
        @reservations = Reservation.where(dateFrom: date..(date + 24.hours)).take(5)
        @date = date.strftime("%B %e, %Y")
        @has_picked_date = true
      elsif params[:reservation][:purpose]
        @purpose = params.dig("reservation", "purpose")
      elsif params[:reservation][:reservation_records_attributes]
        id = params[:reservation][:reservation_records_attributes].values.last[:item_id]
        quantityCount = Item.find(id.to_i).quantity
      end
    end
  end

  def destroy
    @reservation.destroy
    redirect_to reservations_path
  end

  def cancel
  end

  def push_cancel
    if current_user.valid_password?(params[:pass])
      @reservation.update(remarks: params[:reason], status: "Cancelled")
      flash[:success] = "Reservation Canceled."
      title = "Canceled Reservation"
      message_content = "Your reservation has been cancelled due to #{params[:reason]}. Please approach the admin to know more."
      @message = Message.new(title: title, content: message_content, user_id: @reservation.user_id, reservation_id: @reservation.id)
      @message.save
    end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_admin_form.html.erb
<div id="sample"></div>


<%= simple_form_for @reservation do |f| %>
  <div class="row">
    <div class="col-6">
      <b><%= f.label :dateFrom, "Date of Reservation :  " %></b>
      <%= f.date_field :dateFrom, min: (Date.today + 3.days), data: { remote: true }, value: @date_param %>
    </div>
  </div>
  <b><%= f.input :timeFrom, input_html: {autocomplete: 'off'}, start_hour: 7, end_hour: 21 %></b>
  <b><%= f.input :timeTo, input_html: {autocomplete: 'off'}, start_hour: 7, end_hour: 21%></b>
  <% if current_user.admin? %>
    <b><%= f.input :purpose, collection: Reservation::ADMIN_PURPOSE, input_html: { data: { remote: true } },prompt: "", selected: @purpose %></b>
  <% else %>
    <b><%= f.input :purpose, collection: Reservation::PURPOSE, input_html: { data: { remote: true } },prompt: "", selected: @purpose %></b>
  <% end %>
  <br>
  <div id="purposeForm">
  </div>
  <% if @has_picked_date %>
    <div class="mb-3 mt-3">
      <%= f.fields_for :reservation_records do |reserve| %>
        <%= render "reservation_item", f: reserve %>
      <% end %>
      <%= link_to_add_association "Reserve Facility", f, :reservation_records, partial: "reservation_facility", class: "btn btn-primary" %>
      <%= link_to_add_association "Reserve Equipment", f, :reservation_records, partial: "reservation_item", class: "btn btn-primary" %>
    </div>
    <%= f.button :submit, class: "btn btn-success"%>
  <% end %>
<% end %>

app/views/reservations/_cancel.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
    <p>Cancel this Reservation?</p>
  </div>
<div class="modal-footer">
  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
  <%= link_to "Cancel", cancel_reservation_path(reservation),class: "btn btn-danger float-left"%>
</div>

app/views/reservations/_records.html.erb
<% if @reservations.blank? %>

<h4>No Reservations for <%= @date %> </h4>

<% else %>
  <h4>Reservations for <%= @date %> </h4>
  <table class="table table-striped">
    <tr>
      <th>Equipment / Facility </th>
      <th>Quantity </th>
      <th>Time From</th>
      <th>Time To</th>
      <th>Reserved by</th>
    </tr>
  <% @reservations.each do |res| %>
  <% res.reservation_records.each do |record| %>
    <tr>
        <td>
            <%= record.facility_id.present? ? record.facility.name : record.item.name %>
        </td>
        <% if record.quantity %>
          <td> <%= record.quantity %> </td>
        <% else %>
          <td> N/A </td>
        <% end %>
        <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %></td>
        <td> <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
        <td> <%= "#{res.user&.firstName} #{res.user&.lastName}"%> </td>
    </tr>
    <% end %>
  <% end %>
  </table>
<% end %>

app/views/reservations/_reservation_facility.html.erb
<div class="nested-fields">
  <b style="float:left"><%= f.input :facility_id, collection: Facility.order(:name).where("status == 'Active'"), prompt: " ",input_html:{style: 'width:610px'} %></b>
  </br>
  <%= link_to_remove_association "X", f, class: "btn btn-danger", style: 'float:right' %>
</div>

app/views/reservations/_reservation_item.html.erb
<div class="nested-fields">
  <b style="float:left"><%= f.input :item_id, collection: Item.order(:name).where("quantity != 0"), input_html: { onchange: "checkMaxQuantity(this.value)",style: 'width:610px'}%></b>
  </br>
  <%= link_to_remove_association "X", f, class: "btn btn-danger",style: 'float:right' %>
  </br></br></br>
  <h6 style="color:red" id="maxQuant"> </h6>
  <b style="float:left"><%= f.input :quantity, input_html: { max: 200, min: 1, style: 'width:610px'} %></b>
  
</div>

app/views/reservations/cancel.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8 content-section">
      <h4>Reservation Date: <%= @reservation.dateFrom %></h4>
      <h4>Reservation Time: <%= DateTime.parse(@reservation.timeFrom.to_s).strftime("%I:%M%p") %> to <%= DateTime.parse(@reservation.timeTo.to_s).strftime("%I:%M%p") %></h4>
      <h3></h3>
        <%= form_tag submit_cancelation_path(@reservation) do %>
        <%= radio_button_tag(:reason, "School Event") %>
        <%= label_tag(:label, "School Event") %>
        <%= radio_button_tag(:reason, "Class Suspension") %>
        <%= label_tag(:label, "Class Suspension") %>
        <br>
        <%= label_tag(:labl, "Enter your password:", class: "mr-2")%>
        <%= password_field_tag(:pass) %>
        <br>
        <%= submit_tag('Submit',class: "btn btn-md mt-2") %>
        <% end %>
    </div>
    <div class="col-2"></div>
  </div>

</div>

app/views/reservations/cancel.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'cancel') %>");
$("#modal-windo").modal();

app/views/reservations/index.js.erb
$('#reservationListIndex').html("<%= escape_javascript(render("reservation_list"))%>");

app/views/reservations/purposeForm.js.erb
<% if @purpose == "ACADEMIC" %>
  $('#ProfOpts').addClass('show').addClass('form-control');
  $('#orgOpts').addClass('hide');
<% else %>
  $('#ProfOpts').addClass('hide');
  $('#orgOpts').addClass('show').addClass('form-control');
<% end %>

app/views/reservations/reservation_data_pdf.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "notification_mailer" %>

  <div class="container">
    <div class="row">
      <div class="col-sm-4">  
          <%= wicked_pdf_image_tag('Logo.png', width: '90px', height:'90px', align: "left") %>
          <%= wicked_pdf_image_tag('sj_logo.png', width: '90px', height:'90px', align: 'right') %>
      </div>
      <div class="col-sm-4 mb-4">  
        <p class="text-center">Polytechnic University of the Philippines</p>
        <p class="text-center">San Juan Campus</p>
        <p class="text-center">Online Equipment and Facilities Reservation System</p>
      </div>
      <!-- <div class="col-20">
         <%= wicked_pdf_image_tag('sj_logo.png', width: '90px', height:'90px', align: 'right') %>
        </div> -->
    </div>
    <div class="rep-title">
      <% if @status.present? %>
      <h1 class="text-center">
       <%=@status %> Reservations from <%= @from %> to <%= @to %>
      </h1>
      <% end %>
    </div>
    <div>
        <table class="table table-striped">
  <thead class="thead-dark">
    <tr>
        <th>Equipment / Facility </th>
        <th>Quantity </th>
        <th>Purpose</th>
        <th>Status</th>
        <th>Date</th>
        <th>Time</th>
        
    </tr>
  </thead>
  <% @reservations.each do |res| %>
  <% res.reservation_records.each do |record| %>
    <tr>
        <td>
            <%= record.facility_id.present? ? record.facility.name : record.item.name %>
        </td>
        <% if record.quantity %>
          <td> <%= record.quantity %> </td>
        <% else %>
          <td> N/A </td>
        <% end %>
        <td><%=  record.reservation.purpose %></td>
        <td><%= record.reservation.status %></td>
        <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
        <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %> - <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
    </tr>
    <% end %>
  <% end %>
</table>
        <hr>
        <div class="total">
          <p><h2 class="text-right">Total: <%= @reservations.length %></h2></p>
        </div>
    </div>
  </div>

app/views/reservations/reservation_pdf.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "notification_mailer" %>
<div class="logo-container">
    <div class="logo"></div>
    <p class="name">PUPSJ Online Facility and Equipment Reservation</p>
  </div>
  <div class="email-wrapper">
    <header class="confirmation">
      <p class="greetings">Good Day, <%= @user.firstName %>!</p>
      <p class="info">Congratulations! Your reservation for <span class="highlight-bold"><%= @reservation.dateFrom.strftime("%b %e, %Y") %></span> from</p>
      <p class="info"><span class="highlight-bold"><%= @reservation.timeFrom.strftime("%I:%M %p") %></span> to <span class="highlight-bold"><%= @reservation.timeTo.strftime("%I:%M %p") %></span>  has been confirmed.</p>
      <p class="greetings">Your Reservation Reference Number:</p>
      <p class="greetings"><%= @reservation.reference %></p>
    </header>
    <div class="content-container">
      <div class="details">
        <div class="reservation-info">
          <h3 class="highlight-text trip-label">DETAILS</h3>
        </div>
        <div class="reservation-info">
          <p>
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                    <th>Equipment / Facility </th>
                    <th>Quantity </th>
                    <th>Date</th>
                    <th>Time From</th>
                    <th>Time To</th>
                </tr>
              </thead>
              <% @reservation.reservation_records.each do |record| %>
                <tr>
                    <td>
                        <%= record.facility_id.present? ? record.facility.name : record.item.name %>
                    </td>
                    <% if record.quantity %>
                      <td> <%= record.quantity %> </td>
                    <% else %>
                      <td> N/A </td>
                    <% end %>
                    <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
                    <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %></td>
                    <td> <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
                </tr>
              <% end %>
            </table>
          </p>
        </div>
        <div class="reservation-info">
          <p>You may show this file to claim your reservation</p>
          <p>Please Claim your Reservation on time</p>
        </div>
        <div class="reservation-info">
          <p>If you have any questions for your reservation, please go to Sir Roehl.</p>
        </div>
      </div>
    </div>
  </div>

app/views/reservations/show.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <h2>
    <%= @reservation.purpose %>
  </h2>
  <h3>
    <%= @reservation.dateFrom %>
  </h3>
  <h4>
    <%= @reservation.dateTo %>
  </h4>
  <h4>
    <%= @reservation.timeFrom %>
  </h4>
  <h4>
    <%= @reservation.timeTo %>
  </h4>
  <%= link_to "Edit", edit_reservation_path(@reservation), class: "btn btn-primary" %>
  <%= link_to "Delete", reservation_path(@reservation), method: :delete, data: { confirm: "Are you sure? "},class: "btn btn-danger" %>

</div>

app/views/reservations/studentReservation.html.erb
<%= render 'layouts/header' %>
<div class="container pt-4 mt-5">
<div class="pt-4 mt-3"><%= render 'layouts/messages' %></div>
<div class="row mb-2">
  <%= render 'layouts/sidebar' %>
  <div class="col-8">
    <div class="shadow p-4 card-calendar", id="reservationForm">
      <h2>Reservation</h2>
      <hr>
      <%= render 'form' %>
    </div>
  </div>
</div>
</div>

app/views/reservations/studentReservation.js.erb
<% if @purpose.present? %>
  $('#purposeForm').html("<%= escape_javascript(render("purpose"))%>");
<% else %>
  $('#reservationForm').html("<%= escape_javascript(render("form"))%>");
  $('#sample').html("<%= escape_javascript(render("records"))%>");
<% end %>