config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  resources :facilities
  resources :items, :path => 'equipment'
  resources :organizations
  resources :reservations
  resources :field_of_studies
  resources :professors
  resources :courses
  devise_scope :user do
  root to: "devise/sessions#new", :as => '/'
  end

  get '/users' => 'pages#users', :as => "users"
  get '/student/dashboard' => 'pages#dashboard'
  get '/student/reservation' => 'reservations#studentReservation'
  get '/student/reservation/:id' => 'reservations#student_view', :as => "view_reservation"
  post '/student/reservation/:id/cancel' => 'reservations#stud_cancel', :as => "student_cancel_reservation"
  get '/student/calendar' => 'pages#calendar'
  get '/student/messages' => 'pages#messages'
  get '/student/messages/:id' => 'pages#show', :as => "message_show"
  get '/admin' => 'pages#index'
  get '/admin_login' => 'pages#admin_login'
  post '/authenticate_admin' => 'pages#authenticate_admin'
  get '/admin/add_user' => 'pages#admin_add_user'
  post '/admin_create_user' => 'pages#admin_create_user'
  post '/student/see_reservations' => 'reservations#see_reservations'
  get '/student/item_list' => 'pages#item_list', :as => "item_list"
  get '/student/facility_list' => 'pages#facility_list', :as => "facility_list"
  get '/data' => 'reservations#data'
  get '/equip' => 'items#export_equipment'
  get '/equip_res' => 'items#export_equipment_pdf'  
  get '/org' => 'organizations#export_organization'
  get '/org_csv' => 'organizations#export_equipment'
  get '/prof' => 'professors#export_equipment'
  get '/prof_csv' => 'professors#export_equipment_csv'
  get '/fac' => 'facilities#export_equipment'
  get '/facs' => 'facilities#export_data'
  get '/fac_pdf' => 'facilities#export_facility_pdf'
  get '/res' => 'reservations#export_equipment'
  get '/cors' => 'courses#export_courses'
  get '/cors_csv' => 'courses#export_equipment'
  get '/res_equips' => 'items#export_equip_res'
  get '/fields' => 'field_of_studies#export_fields_pdf', :as => 'fields_export'
  get '/fields_csv' => 'field_of_studies#export_equipment'
  get '/reservation_today' => 'pages#export_reservation_today'
  get '/cancel_reservation/:id' => 'reservations#cancel', :as => 'cancel_reservation'
  post '/cancel/:id' => 'reservations#push_cancel', :as => 'submit_cancelation'
  get '/organization/new/non_acad' => 'organizations#nonAcadOrg', :as => 'non_acad'
  post '/organization/new/non_acad' => 'organizations#createNonAcadOrg', :as => 'create_non_acad'
  get '/purposes' => 'reservations#purposeForm'
  # get '/update_reservation/:id' => 'reservations#claims', as: => 'claim_time'
  post '/update_reservation/:id' => 'reservations#claims', :as => 'claim_time'
  get '/return/:id' => 'reservations#returnsView', :as => 'return'
  post '/update_reservations/:id' => 'reservations#returns', :as => 'return_time'
  post '/get_item_count' => 'reservations#get_item_count'
  # post '/cancel/:id' => 'reservations#stud_cancel', :as 'stud_cancel'
  # get '/list' => 'reservations#list' as => "list"
  # Edit non acad orgs
  get '/organization/update/:id' => 'organizations#editNonAcadOrg', :as => 'editNonAcad'
  patch '/organization/update/:id' => 'organizations#updateNonAcadOrg', :as => 'updateNonAcad'
  post '/unblock/:id' => 'pages#unblockUser', :as => 'unblock_user'
  post '/block/:id' => 'pages#blockUser', :as => "block_user"
  get "/reservation_pdf" => "reservations#reservation_pdf", as: "reservation_pdf"

  get '/show_item/:id' => "pages#item_show", as: "item_show"

  get '/facility_item/:id' => "pages#facility_show", as: "facility_show"


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get "*any", via: :all, to: "errors#not_found"


  # root to: 'devise/session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  # belongs_to :reservation
  validates :name, presence: true, uniqueness: true
  validates :quantity, presence: true
  has_many :reservation_records, dependent: :destroy

  has_many :specifications, dependent: :destroy
  accepts_nested_attributes_for :specifications, :allow_destroy => true


  def self.search(query: nil)
    query = "%#{query}%"
    where("name LIKE ?", query).order(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :update, :edit, :destroy]
  before_action :authenticate

  def index
    # @items = Item.paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
    search = params[:search_trips]
    @items = if search.blank?
              Item.paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
            else
              Item.search(query: search).paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
            end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      # binding.pry
      flash[:success] = "Equipment Added."
      redirect_to items_path
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @item.update(item_params)
      flash[:success] = "Equipment Updated."
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def edit
    if params[:item]
      if params[:item][:specifications_attributes]
      end
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "Equipment Deleted."
    redirect_to items_path
  end

  def test

  end

  def export_equipment
    respond_to do |format|
      format.csv do
        equipments = Item.all
        export_headers("#{Time.zone.now}-Equipments")
        self.response_body = export_for_equipment(equipments)
      end
    end
  end

  def export_equipment_pdf
    @items= Item.all
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "Equipments",:template => "items/equip_data"
      end
    end
  end

  def export_equip_res
    @from = params[:from]
    @to = params[:to]
    @reservations = Reservation.where('dateFrom BETWEEN ? AND ?', DateTime.parse(@from), DateTime.parse(@to))
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "Reservation data",:template => "items/equipment_res"
      end
    end
  end

  private

  def authenticate
    if current_user.nil?
    flash[:danger] = "You are unauthorized!"
    redirect_to new_user_session_path
    elsif current_user.student?
      flash[:danger] = "You are unauthorized!"
      redirect_to student_dashboard_path
    end
  end

  def export_headers(label)
    filename = "#{label}-#{Time.zone.today}"
    response.headers["Cache-Control"] = "no-cache"
    response.headers["X-Accel-Buffering"] = "no"
    response.headers["Content-Type"] ||= "text/csv"
    response.headers["Content-Disposition"] =
      "attachment; filename=#{filename}.csv"
    response.headers["Content-Transfer-Encoding"] = "binary"
  end

  def export_for_equipment(entries)
    header2 = ["Equipment Master List"].to_csv
    header = ["Equipment Name", "Quantity"].to_csv
    Enumerator.new do |row|
      entries.each_with_index do |x, y|
        row << header2 if y == 0
        row << header if y == 0
        row << [x.name, x.quantity].to_csv
      end
    end
  end

  def item_params
    params.require(:item).permit(:name, :quantity, specifications_attributes: [:id, :field, :content, :_destroy])
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
<div class="col-2"></div>
<%= simple_form_for @item, :html => {class:"form-horizontal pt-3 col-8 align-center content-section", role:"form"} do |f| %>
<div class="form-group">
  <div class="form-row">
    <div class="form-inline col-3">
      <h5 class="pb-2">
        <b><%= f.label :name, label: 'Equipment Name' %></b>
      </h5>
    </div>
    <div class="col-9">
      <%= f.input :name, label: false, input_html: {autocomplete: 'off'} %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="form-row">
    <div class="form-inline col-3">
      <h5 class="pb-2">
        <b><%= f.label :quantity, label: 'Quantity' %></b>
      </h5>
    </div>
    <div class="col-9">
      <%= f.input :quantity, label: false %>
    </div>
  </div>
</div>
  <div id="links">
       <%= link_to_add_association "Add Specification", f, :specifications, partial: "specifications", class: "btn btn-primary mr-2 float-left" %>
  </div>
<%= f.button :submit, class: "btn-success float-right", value: "Submit" %>
<%= link_to "Back", items_path, class: "btn btn-secondary  mr-2 float-right"%>

<% end %>
<div class="col-2"></div>
</div>

app/views/items/_header.html.erb
<header id="main-header" class="py-2 bg-success text-white mb-3 p-2">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1><i data-feather="speaker"></i> Equipment</h1>
        </div>
      </div>
    </div>
  </header>

app/views/items/_items.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
    <th>Quantity</th>
    <th colspan="2"></th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td>
    <% item&.specifications&.each do |spec| %>
    <ul>
    <li><b><%= spec&.field %>: </b><%= truncate(spec&.content, :length => 50) %></li>
    </ul>
    <% end %>
    </td>
    <td><%= item.quantity %></td>
    <td>
        <%= link_to edit_item_path(item), class: "btn btn-primary btn-sm float-left" do %>
          <span class="small" data-feather="edit-2"></span> Edit
        <% end %>
    </td>

  </tr>
<% end %>
</table>
</div>
<ul class="apple_pagination mt-2">
<%= will_paginate @items, parmas: { format: :js } %>
</ul>

app/views/items/_specifications.html.erb
<div class="nested-fields">
  <div class="form-group">
    <div class="form-row">
      <div class="col-3">
        <h5 class="pb-2">
          <b><%= f.label :field, label: "Title",input_html:{class: 'form-inline'} %></b>
        </h5>
      </div>
      <div class="col-8">
        <%= f.input :field, label: false, prompt: " ",input_html:{class: 'form-inline'} %> 
      </div>
      <div class="col-1">
        <%= link_to_remove_association  "x", f, class: "btn btn-danger form-inline"  %>
      </div>
      
    </div>
  </div>
  <div class="form-group">
      <div class="form-row">
        <div class="col-3">
          <h5 class="pb-2">
            <b><%= f.label :content, label: "Content",input_html:{class: 'form-inline'} %> </b>
          </h5>
        </div>
        <div class="col-8">
          <%= f.input :content, label: false, prompt: " ",input_html:{class: 'form-inline'} %>
        </div>
      </div>
    </div>
  
</div>

app/views/items/_specs_edit.html.erb
<% if f.object %>
  <div class="nested-fields">
  <div class="form-group">
    <div class="form-row">
      <div class="col-3">
        <h5 class="pb-2">
          <b><%= f.label :field, label: "Title",input_html:{class: 'form-inline'} %></b>
        </h5>
      </div>
      <div class="col-8">
        <%= f.input :field, label: false, prompt: " ",input_html:{class: 'form-inline'} %> 
      </div>
      <div class="col-1">
        <%= link_to_remove_association  "x", f, class: "btn btn-danger form-inline", data: { confirm: "Are you sure? This action is irreversible. "} %>
      </div>
      
    </div>
  </div>
  <div class="form-group">
      <div class="form-row">
        <div class="col-3">
          <h5 class="pb-2">
            <b><%= f.label :content, label: "Content",input_html:{class: 'form-inline'} %> </b>
          </h5>
        </div>
        <div class="col-8">
          <%= f.input :content, label: false, prompt: " ",input_html:{class: 'form-inline'} %>
        </div>
      </div>
    </div>
  
</div>
<% end %>

app/views/items/edit.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <div class="row">
<div class="col-2"></div>
<%= simple_form_for @item, :html => {class:"form-horizontal pt-3 col-8 align-center content-section", role:"form"} do |f| %>
<div class="form-group">
  <div class="form-row">
    <div class="form-inline col-3">
      <h5 class="pb-2">
        <b><%= f.label :name, label: 'Equipment Name' %></b>
      </h5>
    </div>
    <div class="col-9">
      <%= f.input :name, label: false, input_html: {autocomplete: 'off'} %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="form-row">
    <div class="form-inline col-3">
      <h5 class="pb-2">
        <b><%= f.label :quantity, label: 'Quantity' %></b>
      </h5>
    </div>
    <div class="col-9">
      <%= f.input :quantity, label: false %>
    </div>
  </div>
</div>
  <%= f.fields_for :specifications do |specs| %>
          <%= render "specs_edit", f: specs %>
    <% end %>

  <div id="links">
       <%= link_to_add_association "Add Field", f, :specifications, partial: "specifications", class: "btn btn-primary mr-2 float-left" %>
  </div>
<%= f.button :submit, class: "btn-success float-right", value: "Submit" %>
<%= link_to "Back", items_path, class: "btn btn-secondary  mr-2 float-right", data: { confirm: "Are you sure? Unsaved changes will be lost. "}%>
<% end %>
<div class="col-2"></div>
</div>
</div>

app/views/items/equip_data.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "notification_mailer" %>

  <div class="container">
    <div class="row">
        <div class="col-sm-4">  
            <%= wicked_pdf_image_tag('Logo.png', width: '75px', height:'75px', align: "left") %>
            <%= wicked_pdf_image_tag('sj_logo.png', width: '75px', height:'75px', align: 'right') %>
        </div>
      <div class="col-sm-4 mb-4">  
        <p class="text-center">Polytechnic University of the Philippines</p>
        <p class="text-center">San Juan Campus</p>
        <p class="text-center">Online Equipment and Facilities Reservation System</p>
      </div>
      <!-- <div class="col-20">
         <%= wicked_pdf_image_tag('sj_logo.png', width: '75px', height:'75px', align: 'right') %>
        </div> -->
    </div>
    <div class="rep-title">
      <h1 class="text-center">Equipment Master List</h1>
    </div>
    <div>
        <table class="table table-striped">
            <tr>
              <th class="text-left">Name</th>
              <th class="text-left"></th>
              <th class="text-left">Quantity</th>
            </tr>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td>
                <% item&.specifications&.each do |spec| %>
                <ul>
                <li><b><%= spec&.field %>: </b><%= truncate(spec&.content, :length => 50) %></li>
                </ul>
                <% end %>
              </td>
              <td><%= item.quantity %></td>
            </tr>
          <% end %>
          </table>
        <hr>
        <div class="total">
          <p><h2 class="text-right">Total: <%= @items.length %></h2></p>
        </div>
    </div>
  </div>
  

app/views/items/equipment_res.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "notification_mailer" %>

  <div class="container">
    <div class="row">
      <div class="col-sm-4">  
          <%= wicked_pdf_image_tag('Logo.png', width: '90px', height:'90px', align: "left") %>
          <%= wicked_pdf_image_tag('sj_logo.png', width: '90px', height:'90px', align: 'right') %>
      </div>
      <div class="col-sm-4 mb-4">  
        <p class="text-center">Polytechnic University of the Philippines</p>
        <p class="text-center">San Juan Campus</p>
        <p class="text-center">Online Equipment and Facilities Reservation System</p>
      </div>
      <!-- <div class="col-20">
         <%= wicked_pdf_image_tag('sj_logo.png', width: '90px', height:'90px', align: 'right') %>
        </div> -->
    </div>
    <div class="rep-title">
      <h2 class="text-center">Equipments Reserved from <%= @from %> to <%= @to %></h2>
    </div>
    <div>
        <table class="table table-striped">
  <thead class="thead-dark">
    <tr>
        <th>Equipment / Facility </th>
        <th>Quantity </th>
        <th>Purpose</th>
        <th>Date</th>
        <th>Time</th>
        <th></th>
    </tr>
  </thead>
  <% @reservations.each do |res| %>
  <% res.reservation_records.each do |record| %>
  <% if record.item_id.present?%>
    <tr>
        <td>
            <%= record.item.name %>
        </td>
          <td> <%= record.quantity %> </td>
        <td><%=  record.reservation.purpose %></td>
        <td><%= record.reservation.dateFrom.strftime("%b %e, %Y") %></td>
        <td> <%= record.reservation.timeFrom.strftime("%I:%M %p") %> - <%= record.reservation.timeTo.strftime("%I:%M %p") %></td>
    </tr>
  <% end %>
    <% end %>
  <% end %>
</table>
        <hr>
    </div>
  </div>

app/views/items/index.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <div class="row">
    <div class="col-8"></div>
    <div class="col-4">
    <%= form_tag items_path, method: :get, class: "form-group", remote: true do %>
        <%= text_field_tag :search_trips, nil,class: "form-control", placeholder: "Search..", autocomplete: :off %>
      <% end %>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
    <h4>
    <!-- <a href="/items/new" class="btn btn-success float-right">
    <span class="small" data-feather="plus"></span>
      Add item</a> -->
    <%= link_to  new_item_path, class: "btn btn-success float-right" do %>
          <span class="small" data-feather="plus"></span> Add Equipment
    <% end %>
     <button type="button" class="btn btn-info btn-lg mb-2" data-toggle="modal" data-target="#equipmentExport"><span class="medium" data-feather="external-link"></span> Export All</button>
    <%= form_tag res_equips_path(format: :pdf), target: 'blank',class: 'form-row', method: :get do %>
    <%= label_tag :label, "Equipment reserved from: ", class:"mt-1" %>
    <%= text_field_tag :from ,"", class: 'form-control col-2 mr-2', id: 'firstDate', autocomplete: :off %>
    <%= text_field_tag :to,"", class: 'form-control col-2 mr-2', id: 'secondDate', autocomplete: :off %>
    <%= submit_tag 'Get Data', class: 'btn btn-secondary' %>
    <% end %>
    </h4>
    </div>
  <div class="modal fade" id="equipmentExport" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content text-centered">
        <div class="modal-header text-centered">
          <h4 class="modal-title">Export via</h4>
        </div>
        <div class="modal-body">
          <%= link_to "CSV",
                equip_path(format: :csv), class: "btn btn-primary"%> OR
          <%= link_to "PDF",
                equip_res_path(format: :pdf), target: 'blank', class: "btn btn-danger"%>
        </div>
      </div>
    </div>
  </div>
    <div id="itemsList"><%= render 'items' %></div>
</div>

app/views/items/index.js.erb
$('#itemsList').html("<%= escape_javascript(render("items"))%>");

app/views/items/new.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<%= render 'layouts/navbar' %>
<%= render 'header' %>
<div class="container">
  <h2>
    <%= @item.propertyNumber %>
  </h2>
  <h3>
    <%= @item.name %>
  </h3>
  <h4>
    <%= @item.category %>
  </h4>
  <%= link_to "Edit", edit_item_path(@item), class: "btn btn-primary" %>
  <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure? "},class: "btn btn-danger" %>

</div