config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  resources :facilities
  resources :items, :path => 'equipment'
  resources :organizations
  resources :reservations
  resources :field_of_studies
  resources :professors
  resources :courses
  devise_scope :user do
  root to: "devise/sessions#new", :as => '/'
  end

  get '/users' => 'pages#users', :as => "users"
  get '/student/dashboard' => 'pages#dashboard'
  get '/student/reservation' => 'reservations#studentReservation'
  get '/student/reservation/:id' => 'reservations#student_view', :as => "view_reservation"
  post '/student/reservation/:id/cancel' => 'reservations#stud_cancel', :as => "student_cancel_reservation"
  get '/student/calendar' => 'pages#calendar'
  get '/student/messages' => 'pages#messages'
  get '/student/messages/:id' => 'pages#show', :as => "message_show"
  get '/admin' => 'pages#index'
  get '/admin_login' => 'pages#admin_login'
  post '/authenticate_admin' => 'pages#authenticate_admin'
  get '/admin/add_user' => 'pages#admin_add_user'
  post '/admin_create_user' => 'pages#admin_create_user'
  post '/student/see_reservations' => 'reservations#see_reservations'
  get '/student/item_list' => 'pages#item_list', :as => "item_list"
  get '/student/facility_list' => 'pages#facility_list', :as => "facility_list"
  get '/data' => 'reservations#data'
  get '/equip' => 'items#export_equipment'
  get '/equip_res' => 'items#export_equipment_pdf'  
  get '/org' => 'organizations#export_organization'
  get '/org_csv' => 'organizations#export_equipment'
  get '/prof' => 'professors#export_equipment'
  get '/prof_csv' => 'professors#export_equipment_csv'
  get '/fac' => 'facilities#export_equipment'
  get '/facs' => 'facilities#export_data'
  get '/fac_pdf' => 'facilities#export_facility_pdf'
  get '/res' => 'reservations#export_equipment'
  get '/cors' => 'courses#export_courses'
  get '/cors_csv' => 'courses#export_equipment'
  get '/res_equips' => 'items#export_equip_res'
  get '/fields' => 'field_of_studies#export_fields_pdf', :as => 'fields_export'
  get '/fields_csv' => 'field_of_studies#export_equipment'
  get '/reservation_today' => 'pages#export_reservation_today'
  get '/cancel_reservation/:id' => 'reservations#cancel', :as => 'cancel_reservation'
  post '/cancel/:id' => 'reservations#push_cancel', :as => 'submit_cancelation'
  get '/organization/new/non_acad' => 'organizations#nonAcadOrg', :as => 'non_acad'
  post '/organization/new/non_acad' => 'organizations#createNonAcadOrg', :as => 'create_non_acad'
  get '/purposes' => 'reservations#purposeForm'
  # get '/update_reservation/:id' => 'reservations#claims', as: => 'claim_time'
  post '/update_reservation/:id' => 'reservations#claims', :as => 'claim_time'
  get '/return/:id' => 'reservations#returnsView', :as => 'return'
  post '/update_reservations/:id' => 'reservations#returns', :as => 'return_time'
  post '/get_item_count' => 'reservations#get_item_count'
  # post '/cancel/:id' => 'reservations#stud_cancel', :as 'stud_cancel'
  # get '/list' => 'reservations#list' as => "list"
  # Edit non acad orgs
  get '/organization/update/:id' => 'organizations#editNonAcadOrg', :as => 'editNonAcad'
  patch '/organization/update/:id' => 'organizations#updateNonAcadOrg', :as => 'updateNonAcad'
  post '/unblock/:id' => 'pages#unblockUser', :as => 'unblock_user'
  post '/block/:id' => 'pages#blockUser', :as => "block_user"
  get "/reservation_pdf" => "reservations#reservation_pdf", as: "reservation_pdf"

  get '/show_item/:id' => "pages#item_show", as: "item_show"

  get '/facility_item/:id' => "pages#facility_show", as: "facility_show"


  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get "*any", via: :all, to: "errors#not_found"


  # root to: 'devise/session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container" >
  <footer class="footer" style="color:white">
    <small>
      <a href="" style="color:white">Online Facility and Equipment Reservation System</a>
      by <a href="" style="color:white"> BSIT 4-1</a>
    </small>
    <nav>
      <ul>
        <li > <% unless user_signed_in? %>
          <small class="float-left" ><%= link_to "Admin", admin_login_path, style:"color:white"%></small>
          <% else %>
          
          <% end %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="headerContainer pb-5 mb-5" style="z-index: 100">
    <div class="logo mt-2 ml-4">
      <%= image_tag("Logo.png", width: '75px',height: "75px")%>
    </div>
    <span class="header banner">
      <h3 class="banner pl-2">
      <font face="Century Gothic"><a href="/" style="color: white;" >Polytechnic University of the Philippines - San Juan Campus
          <br>Online Equipment and Facilities Reservation System
        </a></font>
      </h3>
    </span>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>' style="background-color:lightgreen">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
  <div class="container">
    <a href="/admin" class="navbar-brand">PUPSJ-OEFRS</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item px-2">
          <a href="/users" class="nav-link">Users</a>
        </li>
        <li class="nav-item px-2">
          <a href="/reservations" class="nav-link">Reservations</a>
        </li>
        <li class="nav-item px-2">
          <a href="/equipment" class="nav-link">Equipment</a>
        </li>
        <li class="nav-item px-2">
          <a href="/facilities" class="nav-link">Facilities</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Miscellaneous
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Professors", professors_path, class: "dropdown-item" %>
              <%= link_to "Field Of Study", field_of_studies_path, class: "dropdown-item" %>
              <%= link_to "Course", courses_path, class: "dropdown-item" %>
              <a href="/organizations" class="dropdown-item">Organizations</a>
            </div>
          </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="contents-section col-sm-12 col-lg-3 mb-2 h-25 shadow p-4" style="background-color: maroon;">
  <h1 class="h2" style="color: white">Menu
    <hr class="bg-white">
  </h1>
  <div class="">
    <h5>
      <font face="Century Gothic" ><a href="/student/dashboard" style="color: white;">Dashboard</a></font>
    </h5>
    <h5>
      <font face="Century Gothic" ><a href="/student/messages" style="color: white;">Notification</a></font>
    </h5>
  </div>
  <h5>
    <font face="Century Gothic" ><a href="/student/calendar" style="color: white;">Calendar</a></font>
  </h5>
  <h5>
    <font face="Century Gothic" ><a href="/student/item_list" style="color: white;">Equipment</a></font>
  </h5>
  <h5>
    <font face="Century Gothic" ><a href="/student/facility_list" style="color: white;">Facilities</a></font>
  </h5>
  
  <div>
    <h5>
  <font face="Century Gothic" ><%= link_to 'Log out', destroy_user_session_path, method: :delete, style: 'color:white' %></font></h5>
  </div>
</div>

app/views/layouts/_username.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="">
  <b style="font-size:50px"><h2 style:'color:white; font-size:50px'>Welcome <%= current_user.firstName %></b> <i class="fa fa-user" style="font-size:55px"></i></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OEFRS | Polytechnic University of the Philippines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet"' %>
    <%= stylesheet_link_tag  "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" %>

  </head>

  <body style="background-color: grey;  ">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.js' %>
    <%= javascript_include_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js' %>
    <%= javascript_include_tag 'custom' %>

  </body>
</html>